# Generated by Django 5.2.3 on 2025-06-20 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_remove_score_player_name_remove_score_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='score',
            name='cpu_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='player1_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='player2_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
